version: '3.6'
services: 

  musicbrainz-api:
    image: musicbrainz-api
    container_name: musicbrainz-api
    build:
      context: .
      dockerfile: src/WebApi.MusicBrainz/Dockerfile
    environment:
      - Serilog:MinimumLevel:Default=Information
      - Serilog:WriteTo:1:Name=Seq
      - Serilog:WriteTo:1:Args:serverUrl=http://musicbrainz-seq:5341
      - Serilog:Properties:ApplicationName=MusicBrainz API
      - ConnectionStrings:MssqlDbOptions=Server=musicbrainz-sql,1433;database=MusicBrainz;uid=sa;pwd=Password1

    ports:
      - "5000:80"
    networks:
      - musicbrainz-network

networks:
    musicbrainz-network:
      name: musicbrainz-processing-network